### ISSUE TITLE
上传是可以，能不能简化下流程

### ISSUE THREAD

**Issue by hu9msbedu** [onestark/alfred-workflow-qshell#1]
你好，流程能成功，能不能简化一下流程。
截图----上传求牛---得到地址copy。

**Comment by Teraflopst** [comment]
> 你好，流程能成功，能不能简化一下流程。
> 截图----上传求牛---得到地址copy。

还是有人需要这些功能的。现在有很多图形化工具可以满足你的要求，例如 [iPic](https://sspai.com/post/39965)、[PicGo](https://github.com/Molunerfinn/PicGo)。

**Comment by hu9msbedu** [comment]
感谢你的作品和推荐。
